### ISSUE TITLE
is it work on fedora 8 ?

### ISSUE THREAD

**Issue by s4miii** [Error996/bdvl#1]
first of all thank you for your great job, would you please make a video and setup it step by step with all of features ?
another question is, I wanna test it on an old system(fedora 8) is it possible ? because I saw it's based on 64bit systems ,isn't it ?

thnx again

**Comment by Error996** [comment]
This is just a backup, I am not the original author, but I have tested all x64 systems, and have not tested x86 systems.
Good Luck~！

**Comment by Error996** [comment]
But in theory, there is no problem, but the name of the dependent package required by the specific compilation process may be different, and you need to modify it yourself
